// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uisattzmqxrauurybxxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpc2F0dHptcXhyYXV1cnlieHhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjI4NzUsImV4cCI6MjA2ODk5ODg3NX0.bqAwNx-MN5pM7d22co9-v8mN2CJuyyoygQjWOloXMsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});